version: '3.7'

volumes:
  sharedspace:


services:
  redis:
    image: redis
    ports:
    - "6379:6379"

  centrifugo:
    image: centrifugo/centrifugo
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      centrifugo genconfig --config=/centrifugo/config.json
      centrifugo --config=/centrifugo/config.json --port=8000 --engine=redis --redis_address="redis://redis:6379" --admin
    ports:
    - "8000:8000"
    volumes:
    - "sharedspace:/centrifugo"
    depends_on:
      - redis
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

  api:
    build: ./api
    ports:
     - "5000:5000"
    command: uvicorn app.main:app --host=0.0.0.0 --port=5000 --reload
    volumes:
    - "sharedspace:/centrifugo"
    - "./api:/code"
    depends_on:
      - centrifugo

  web:
    build: ./web
    ports:
     - "8080:8080"
    volumes:
    - "./web/app:/src"
